
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=BGDesk
AppVerName=BGDesk - Suporte
AppPublisher=Thinksoft
AppPublisherURL=boagestao.com.br/bgdesk
AppSupportURL=boagestao.com.br/bgdesk
AppUpdatesURL=boagestao.com.br/bgdesk
DefaultDirName={commonpf}\BGDesk
UninstallDisplayIcon={app}\bgdesk.exe
DefaultGroupName=BGDesk
DisableProgramGroupPage=yes
OutputDir=E:\Instaladores\BGDesk
OutputBaseFilename=bgdesk-suporte-win64
PrivilegesRequired=admin
Compression=lzma                         
SolidCompression=yes
WizardStyle=modern
AllowNoIcons=yes
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Code]
procedure TaskKill(FileName: String);
var
  ResultCode: Integer;
begin
    Exec('taskkill.exe', '/f /im ' + '"' + FileName + '"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
end;

[Languages]                                                                                            
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Files]
Source: "E:\Projetos\bgdesk\build\windows-suporte\*"; DestDir: "{app}";  BeforeInstall: TaskKill('bgdesk.exe'); Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\Projetos\bgdesk\certs\ca.crt"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
             
[INI]
Filename: "{app}\boagestao.url"; Section: "InternetShortcut"; Key: "URL"; String: "boagestao.com.br"

[Icons]
Name: "{group}\BGDesk"; Filename: "{app}\bgdesk.exe"; WorkingDir: "{app}"; Check: not WizardNoIcons
Name: "{commondesktop}\BGDesk"; Filename: "{app}\bgdesk.exe"; WorkingDir: "{app}"; Check: not WizardNoIcons

[Run]
Filename: "cmd"; Parameters: "/C certutil -f -addstore root ""{app}\ca.crt"" "; StatusMsg: "Configurando BGDesk"; WorkingDir: {app}; Flags: waituntilterminated runhidden
Filename: "cmd"; Parameters: "/C netsh advfirewall firewall add rule name=""BGDesk Service"" dir=out action=allow program=""{app}\bgdesk.exe"" enable=yes "; StatusMsg: "Configurando Firewall"; WorkingDir: {app}; Flags: waituntilterminated runhidden
Filename: "cmd"; Parameters: "/C netsh advfirewall firewall add rule name=""BGDesk Service"" dir=in action=allow program=""{app}\bgdesk.exe"" enable=yes "; StatusMsg: "Configurando Firewall"; WorkingDir: {app}; Flags: waituntilterminated runhidden
Filename: "cmd"; Parameters: "/C sc create BGDesk binpath=""{app}\bgdesk.exe --service"" start=auto DisplayName=""BGDesk Service"""; StatusMsg: "Criando Serviço"; WorkingDir: {app}; Flags: waituntilterminated runhidden
Filename: "cmd"; Parameters: "/C sc start BGDesk"; StatusMsg: "Iniciando Serviço"; WorkingDir: {app}; Flags: waituntilterminated runhidden

Filename: "{app}\bgdesk.exe"; Description: "{cm:LaunchProgram,BGDesk}"; Flags: runascurrentuser nowait postinstall skipifsilent

[UninstallRun]
Filename: "cmd"; Parameters: "/C sc stop BGDesk"; Flags: waituntilterminated runhidden
Filename: "cmd"; Parameters: "/C sc delete BGDesk"; Flags: waituntilterminated runhidden
Filename: "cmd"; Parameters: "/C taskkill /f /im bgdesk.exe"; Flags: waituntilterminated runhidden 

[UninstallDelete]
Type: files; Name: "{app}\boagestao.url"

