#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/bgdesk/bgdesk /usr/bin/bgdesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/bgdesk.service ]; then
			rm /etc/systemd/system/bgdesk.service /usr/lib/systemd/system/bgdesk.service /usr/lib/systemd/user/bgdesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/bgdesk/files/systemd/bgdesk.service /usr/lib/systemd/system/bgdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload bgdesk.service: Unit bgdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/bgdesk.service:10: Executable path is not absolute: pkill -f "bgdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/bgdesk.service
		fi
		systemctl daemon-reload
		systemctl enable bgdesk
		systemctl start bgdesk
	fi
fi
